config/routes.rb
Blog::Application.routes.draw do
  get "welcome/index"

   resources :articles do
      resources :comments
   end
   root :to => 'welcome#index'
   

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :text, :title
  has_many :comments, dependent: :destroy
  validates_presence_of :title 
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  attr_accessible :body, :commenter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
    @article=Article.new
 	end
	def create
		@article = Article.new(params[:article])
   
		if @article.save
      render :json => { 
         :status => :ok, 
         :message => "Success!",
         :articles => @article
          }.to_json
		else 
      p "hjgj"
      render :json => { 
         :status => 500, 
         :message => "Failure!",
         :articles => params[:article]
          }.to_json
    end
  end
  def show
    p params[:id]
   	@article =Article.find(params[:id])
    render :json => { 
         :status => 200, 
         :message => "Success!",
         :articles => @article 
          }.to_json
  end	
  def index
    @articles = Article.all
  end	
  
  def edit
    @article =Article.find(params[:id])
    render :json => { 
         :status => 200, 
         :message => "Success!",
         :articles => @article 
          }.to_json
  end
  def update
    @article = Article.find(params[:id])
   
    if @article.update_attributes(params[:article])
      render :json => { 
         :status => 200, 
         :message => "Success!",
         :articles => @article 
          }.to_json
    else
      render :json => { 
         :status => 500, 
         :message => "Failure!",
         :articles => params[:article]
          }.to_json
    end
  end
  def destroy
    @article = Article.find(params[:id])
      if @article.destroy
        p "deleted"
        render :json => { 
           :status => :ok, 
           :message => "success!",
        }.to_json
      else
        p "not deleted"
        render :json => {
            :status => :unprocessable_entity,
            :message => "Failure"
        }.to_json     
      end
  end    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		p "hello"
		@article = Article.find(params[:article_id])
    	@comment = @article.comments.create(params[:comment])
    	 render :json => { 
	         :status => :ok, 
	         :message => "Success!",
	         :articles => @article,
	         :comments => @comment
          }.to_json
    end	
    def destroy
	    @article = Article.find(params[:article_id])
	    @comment = @article.comments.find(params[:id])
	    if @comment.destroy
	    	render :json => { 
	         :status => :ok, 
	         :message => "Success!"
	         }.to_json
	    else
	    	render :json => {
	    		:status => :unprocessable_entity,
	    		:message => "Failure!"
	    	}.to_json
	    end	
	end   
	def index
		p "hello123"
		@article =Article.find(params[:article_id])
		@comments =@article.comments.all
		render :json =>{
			:status =>:ok,
			:message => "Success!",
			:comments =>@comments
		}.to_json
	end 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<%= form_for :article,:html => { :id => 'article' }, url: articles_path do |f| %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>

  </p>
   
  <p>
     <input type="button" name="btn-save" value="submit" id="btn-save"> 
     <input type="text" name="id" value="" id="article_id" class= "hidden"> 
     <input type="button" name="btn-update" value="update" id="btn-update" class="hidden"> 
  </p>
<% end %>

app/views/articles/_index.html.erb
<table id="show_articles">
    <tr>
      <th>Title</th>
      <th>Text</th>
    </tr>
   
    <% @articles.each do |article| %>
      <tr id =<%= article.id %>>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        
        <td><%= link_to_function 'show',"show('#{article.id}')" %></td>
        <td><%= link_to_function 'edit',"edit('#{article.id}')" %></td>
        <td><%= link_to_function 'delete',"destroy('#{article.id}')" %><td>
     
      </tr>
    <% end %>
  </table>

app/views/articles/_show.html.erb
<p>
  <strong>Title:</strong>
  <label id="show_article_title"></label>
</p>
 
<p>
  <strong>Text:</strong>
  <label id="show_article_text"></label>
  
</p>
<h2>Comments</h2>

<h2>Add a comment:</h2>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>  
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Articles</h1>
  <%= link_to_function 'New article','newArticle()' %>
  <%= link_to_function 'Show All Articles','showArticle()' %>
</h1>
<div id="new" class='hidden'>
   <%= render 'article' %>
</div>
<div id="index" class='hidden'> 
   <%= render 'index' %>
</div>
<div id="show" class='hidden'>

</div>  
<div id ="showcomments" class="hidden">    
  <h2>Comments</h2>  
  <table id="show_comments">
    
  </table>
</div>   
<div id ="addcomments" class="hidden">  
  <h2>Add Comments</h2>  
  <%= render 'comments/comment' %>
</div>   

<script src="https://code.jquery.com/jquery-1.11.0.js"></script>
<!-- <script src="/assets/javascripts/custom.js"></script> -->

<script src="/assets/custom.js" type="text/javascript"></script>

app/views/articles/new.html.erb
<h1>
New Article
</h1>
  <%= render 'article' %>

<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<%= form_for :comment,:html => { :id => 'comment' } do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
  <!--   
     <%= f.submit %>
   -->
   <input type="button" id="btn-comment-save" value="Add Comment"></input>
  </p>
<% end %>

app/views/comments/_commentsAll.html.erb
<table id="show_comments">
    <tr>
      <th>Commenter</th>
      <th>Comments</th>
    </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>